name: managementGroups

on:
  push:
    branches-ignore:
      - main
    paths:
        - '**'

  pull_request_target:
    types:
      - closed
  
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  tst:
    uses: ./.github/workflows/tmp-managementGroup.yml
    with:
      topLevelManagementGroupName: gazelle
      location: francecentral
      environment: tst
      policyIdentityResourceId: '/subscriptions/7e88dc1f-a45d-47dc-b986-785db0fea339/resourceGroups/platformIdentity-tst/providers/Microsoft.ManagedIdentity/userAssignedIdentities/id-platformIdentity-tst'
      rbacParameters: './parameters/rbac-tst.bicepparam'
    secrets: inherit

  prod:
    if: github.event_name == 'workflow_dispatch' || ${{ github.event.pull_request.state == 'approved'}}
    uses: ./.github/workflows/tmp-managementGroup.yml
    with:
      topLevelManagementGroupName: gazelle
      location: francecentral
      environment: prod
      policyIdentityResourceId: '/subscriptions/84e64f94-714d-4c07-9f03-f07af8380b36/resourceGroups/platformIdentity-prod/providers/Microsoft.ManagedIdentity/userAssignedIdentities/id-platformIdentity-prod'
      rbacParameters: './parameters/rbac-prod.bicepparam'
    secrets: inherit